# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x3A2e96403d076e9f953166A9E4c61bcD9D164CFe"
    chainName: ethereum
    collateralAddressOrDenom: "0x15700B564Ca08D9439C58cA5053166E8317aa138"
    connections:
      - token: ethereum|mode|0x1BE19a70922Db767E903489CdFacfb567C975BD8
    decimals: 18
    name: deUSD
    standard: EvmHypCollateral
    symbol: deUSD
  - addressOrDenom: "0x1BE19a70922Db767E903489CdFacfb567C975BD8"
    chainName: mode
    connections:
      - token: ethereum|ethereum|0x3A2e96403d076e9f953166A9E4c61bcD9D164CFe
    decimals: 18
    name: supUSD
    standard: EvmHypSynthetic
    symbol: supUSD
